"""initial migration

Revision ID: 28eace97ed5f
Revises: bfbf6719a971
Create Date: 2016-09-08 01:09:24.077174

"""

# revision identifiers, used by Alembic.
revision = '28eace97ed5f'
down_revision = 'bfbf6719a971'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
