"""empty message

Revision ID: a20daf0af51f
Revises: ed053770ad65
Create Date: 2016-10-11 01:44:22.095932

"""

# revision identifiers, used by Alembic.
revision = 'a20daf0af51f'
down_revision = 'ed053770ad65'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
